apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: NDVkM1BlMHFFVWxEcVVrb3Y3SjZpZ1lSZ0trZ3REQzV2Y1JtbGt5alZuejUwZmNwT3B6OUpRUUo5OUFMQUNZZUJqRlhKM3czQUFBQkFDT0c4Y0t3
